---
- name: Install python-apt
  command: apt-get -y install python-apt

- name: Install aptitude (some ubuntus dont have it...)
  command: apt-get -y install aptitude

- name: apt-get upgrade 
  action: apt update_cache=yes upgrade=yes

- name: Install essential packages
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - git
  - mercurial
  - screen
  - bzip2
  - htop
  - vim
  - locate
  - nload
  - python-pycurl
  - zsh
  - apache2-utils

- name: Install build essential package
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - build-essential
  - libssl-dev
  - libdb++-dev
  - libboost-all-dev
  - libqrencode-dev
  - libgmp3-dev
  - libminiupnpc-dev 
  - git
  - zip
  - automake
  - npm
  - curl
  - unzip




- name: curl "http://navcoin.org/files/secp.zip" -o "~/navcoin2/src/secp256k1/secp.zip"
  shell: curl "http://navcoin.org/files/secp.zip" -o "~/navcoin2/src/secp256k1/secp.zip"
  ignore_errors: yes

- name: unzip secp.zip 
  shell: unzip ~/navcoin2/src/secp256k1/secp.zip ~/navcoin2/src/secp256k1/
  ignore_errors: yes


- name: sudo chmod 777 ~/navcoin2/src/secp256k1/* 
  shell: sudo chmod 777 ~/navcoin2/src/secp256k1/*
  ignore_errors: yes

- name: ./autogen.sh
  shell: ./autogen.sh
          chdir=~/navcoin2/src/secp256k1/
  ignore_errors: yes

- name: ./configure --enable-module-recovery
  shell: ./configure --enable-module-recovery
         chdir=~/navcoin2/src/secp256k1/
  ignore_errors: yes

- name: make
  shell: make
         chdir=~/navcoin2/src/secp256k1/
  ignore_errors: yes

- name: make -f makefile.unix -j2
  shell: make -f makefile.unix -j2
         chdir=~/navcoin2/src
  ignore_errors: yes